name: Remove File or Folder

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete file or folder
        run: |
          rm -rf Abhi/demo.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Remove file or folder" || echo "No changes to commit"
          git push
