name: testing secrets variable

on:
  workflow_dispatch

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  test_context_variables:
    runs-on: ubuntu-latest

    steps:
      - name: "Checking secrets varibles"
        run: |
          echo: "Secret value : ${{ secrets.TEST_KEY }}"
